main: net.horizonsend.ion.Ion
name: Ion
version: SNAPSHOT
api-version: 1.18
load: POSTWORLD
author: PeterCrawley
website: https://horizonsend.net
libraries:
  - org.spongepowered:configurate-hocon:4.1.2
  - org.spongepowered:configurate-extra-kotlin:4.1.2
  - org.jetbrains.kotlin:kotlin-reflect:1.6.20
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.20
#soft-depend: [IonCore]